### ISSUE TITLE
FAQ nav click leads to some text missing

### ISSUE THREAD

**Issue by whiletruelearn** [PySangamam/website#10]
Hey @astronomersiva 

I see that clicking on the `FAQ` link navigates to the page in such a way that some text is missing.  I think it should navigate to the beginning of `What is PySangamam?`.

![image](https://user-images.githubusercontent.com/1977850/39416393-36f77638-4c6a-11e8-974a-10762619281b.png)

**Comment by astronomersiva** [comment]
Ah! My bad. Will fix this. Thanks @whiletruelearn !
