### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by bravegnu** [PySangamam/website#11]
A footer which roughly says "Brought to you by the organizers of Chennaipy", and link back to Chennaipy. Also add the copyright info and contact info.

**Comment by astronomersiva** [comment]
@syedjafer was interested in taking this up.

**Comment by syedjafer** [comment]
any reviews , 
syedjafer.me/website/

**Comment by bravegnu** [comment]
- The blue text on the green background is hard to read. 
- The copyright should reflect the copyright assigned to the website repository.
- The spacing between the map and the footer is insufficient.
- The spacing from the footer start to twitter logos is too much
- For the present content, a single line should suffice. (My opinion.)

**Comment by syedjafer** [comment]
![screenshot from 2018-05-01 17-59-34](https://user-images.githubusercontent.com/20949510/39472884-9edbc182-4d69-11e8-9c65-2706ce0853b0.png)

**Comment by syedjafer** [comment]
>The copyright should reflect the copyright assigned to the website repository.
>For the present content, a single line should suffice. (My opinion.)
I can't get these

**Comment by bravegnu** [comment]
@syedjafer The website uses a creative commons license https://github.com/PySangamam/website/blob/gh-pages/LICENSE This needs to be indicated in the footer.

**Comment by bravegnu** [comment]
The "Chennaipy" need not be repeated twice. The first reference can be a link. And there should be something that indicates that it is a link.

**Comment by bravegnu** [comment]
Also see https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license#Example:_Website

**Comment by syedjafer** [comment]
![screenshot from 2018-05-01 19-45-51](https://user-images.githubusercontent.com/20949510/39476121-859c8b8e-4d78-11e8-9fef-f199cba60499.png)

**Comment by astronomersiva** [comment]
I think we can do away with the green background and choose the dark gray shade we have in the inverted containers of the landing page. We can probably have the green bottom border and red top border to keep in line with the navbar.

I feel just one line telling 'Brought to you by ChennaiPy. Text is available under the Creative Commons Attribution - Sharealike License' should be sufficient for now.

**Comment by bravegnu** [comment]
@astronomersiva sounds fine.

**Comment by syedjafer** [comment]
![screenshot from 2018-05-01 20-54-44](https://user-images.githubusercontent.com/20949510/39479124-ecbe4af6-4d81-11e8-85fe-11598cfd40d3.png)

**Comment by bravegnu** [comment]
They grey you have used is darker than the one used in the body. Please use the existing grey. And the font color can be made black.

**Comment by syedjafer** [comment]
![screenshot from 2018-05-02 07-57-30](https://user-images.githubusercontent.com/20949510/39502573-97d8d3c8-4dde-11e8-81b3-c184f9591c3c.png)

**Comment by bravegnu** [comment]
Great! Looks good! Can we link back to https://creativecommons.org/licenses/by-sa/3.0/ instead of our GitHub repo.

@astronomersiva Anyother suggestions here?

**Comment by astronomersiva** [comment]
We can have the green border below this to stay in line with the other pages.

Also, the icons can be a little smaller. cc logo can be in same color and font size as the text.

**Comment by syedjafer** [comment]
![screenshot from 2018-05-02 11-44-22](https://user-images.githubusercontent.com/20949510/39507995-4148daba-4dfe-11e8-9ab2-02de3c18d6e8.png)

**Comment by astronomersiva** [comment]
Addressed in https://github.com/PySangamam/website/pulls/17
