### ISSUE TITLE
Menu Bar Suggestions

### ISSUE THREAD

**Issue by bravegnu** [PySangamam/website#13]
It will be great if we can move the menubar to the top, with the green background. This way it can appear in every page, in the same place. Also the menubar is not visible in mobile devices, without being scrolled to, and even then it is hidden in a button.

**Comment by astronomersiva** [comment]
I will work on the menubar @bravegnu. I didn't want to keep it at the top initially because it looked weird with the green band. But your point on it not being visible initially on mobile devices is valid. I will think of something and change this.

**Comment by astronomersiva** [comment]
@bravegnu Can this issue be closed now?

**Comment by bravegnu** [comment]
@astronomersiva Sure! Thanks for fixing this.
