### ISSUE TITLE
Fix buttons in mobile view.

### ISSUE THREAD

**Issue by astronomersiva** [PySangamam/website#15]
The buttons at the landing section are stuck together when in mobile view. This needs to be addressed.

We could also standardise the button colors and align them with the current theme.

**Comment by syedjafer** [comment]
![screenshot from 2018-05-02 11-21-20](https://user-images.githubusercontent.com/20949510/39507331-0f846fce-4dfb-11e8-8a81-67c0104f16d9.png)

**Comment by astronomersiva** [comment]
Thanks for working on this @syedjafer !

> We could also standardise the button colors and align them with the current theme.

Can you look into this also? Let's not have too many button colors on the website.
