### ISSUE TITLE
Have meta tags for when the website is posted across social media

### ISSUE THREAD

**Issue by shrayasr** [PySangamam/website#18]
Twitter shows a fancy "summary card" when a link is posted based on info available in `<meta>` tags: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary

I'm sure FB / LinkedIn / Whatsapp / Telegram also have such niceties. Let's work on simple images for these.

**Comment by shrayasr** [comment]
Paging @ragupathis @syedjafer. Would any of you like to take this up?

**Comment by ragupathis** [comment]
Yeah , I'm ready to take up @shrayasr .

**Comment by astronomersiva** [comment]
@ragupathis When you do this, add og tags as well.

**Comment by ragupathis** [comment]
Sure @astronomersiva

**Comment by ragupathis** [comment]
Here I tried Link preview with Open Graph(OG) Meta tags, 
I have hosted it on my own server for testing purpose and I tested in below platforms(Attached preview screens).
1) WhatsApp
2) Telegram
3) Twitter
4) LinkedIn

It should work on Fb too(yet to validate with their debugger tool)

Telegram Preview:
![screen shot 2018-05-06 at 5 09 23 pm](https://user-images.githubusercontent.com/5587483/39696300-f50a1bda-520a-11e8-9575-f6518e8123e6.png)

WhatsApp Preview:
![screen shot 2018-05-06 at 5 10 13 pm](https://user-images.githubusercontent.com/5587483/39696327-09ce5c98-520b-11e8-8175-ac90351d70f0.png)

Twitter Preview:
![screen shot 2018-05-06 at 5 12 16 pm](https://user-images.githubusercontent.com/5587483/39696341-158f0dac-520b-11e8-804d-a20f7af5127e.png)

LinkedIn Preview
![screen shot 2018-05-07 at 3 31 12 pm](https://user-images.githubusercontent.com/5587483/39696576-be5bcb14-520b-11e8-9f7d-3456cb826e71.png)


It would be great to add an image to meta tags, it will reflect in link preview. As of now we don't have Logo so pls assist me to choose an appropriate image (Like logo or any).

And also verify and correct the Preview **Text Content** too. 


Thanks.

**Comment by astronomersiva** [comment]
The text looks good to me. Please create a PR with the changes.

@bravegnu what can we do for the logo?

**Comment by bravegnu** [comment]
Let's use the Python logo, till we get our own.

**Comment by astronomersiva** [comment]
Closed by #32.
