### ISSUE TITLE
Throws error when using HTTPS

### ISSUE THREAD

**Issue by shrayasr** [PySangamam/website#20]
![image](https://user-images.githubusercontent.com/240368/39561408-00fc6966-4ec3-11e8-8863-2792193710bf.png)

We should fix this. Hurts credibility.

**Comment by shrayasr** [comment]
@astronomersiva please look into this?

**Comment by bravegnu** [comment]
Does gh support https?

**Comment by shrayasr** [comment]
Apparently, yes https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by syedjafer** [comment]
It may be due to configuration in domain  . For me ( syedjafer.me) it says , 
![screenshot from 2018-05-03 17-32-41](https://user-images.githubusercontent.com/20949510/39575439-2b8c0580-4ef8-11e8-95ec-e94d95430b7b.png)

**Comment by syedjafer** [comment]
also check , https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by astronomersiva** [comment]
@shrayasr  I will check this.

**Comment by astronomersiva** [comment]
@shrayasr One easy fix for this is to enable CloudFlare for the site(we can skip the CDN and just enable HTTPS). We decided to go with Cloudflare anyway so I feel we could fix the issue using that itself instead of thinking about why GH Pages has this weird quirk.

I will look into this nevertheless.

**Comment by astronomersiva** [comment]
![b5592f57-47ea-4a0a-9725-5d5bf406d199](https://user-images.githubusercontent.com/7725225/39612718-6b2f7b5e-4f7f-11e8-9421-34c9e380b0ab.jpeg)


Have you added these @shrayasr ?

**Comment by shrayasr** [comment]
I've just added this in.

**Comment by shrayasr** [comment]
![image](https://user-images.githubusercontent.com/240368/40600051-8c33040a-626d-11e8-899a-632f791c2b45.png)

This is what it says right now

**Comment by shrayasr** [comment]
This is fixed now 👍 Closing
