### ISSUE TITLE
Sponsors Section

### ISSUE THREAD

**Issue by bravegnu** [PySangamam/website#21]
We need to add a sponsors section on the main page. Currently we have 3 confirmed sponsors: Pipal Academy, Clay Labs, OrangeScape. I can provide their logos, when this gets started.

**Comment by astronomersiva** [comment]
@bravegnu please mail me the logos, I will put them up.

**Comment by bravegnu** [comment]
@astronomersiva Created pull request with images #23

**Comment by bravegnu** [comment]
* Pipal: Silver
 * Clay Labs: Patron
 * OrangeScape: Patron (please hold this, need to check with the team)

**Comment by bravegnu** [comment]
We also need to add "Zilogic Systems" in the category "Partner" - Institutional Support Partner

**Comment by astronomersiva** [comment]
Closed by #27
