### ISSUE TITLE
We need a blog

### ISSUE THREAD

**Issue by bravegnu** [PySangamam/website#22]
A blog where can put up articles and announcements is required. Can we put up the necessary infrastructure for this?

**Comment by astronomersiva** [comment]
@bravegnu , the infrastructure is already there.  The [COBC page](http://pysangamam.org/code-of-business-conduct) is how our blogs will look like. I can probably start with a "Hello, World!" blog. I will put something up tonight so that we can share it to the weekend crowd :)

**Comment by astronomersiva** [comment]
I will add the date also to the article (Y) Anything else that you would like to include?

**Comment by bravegnu** [comment]
We need a link to list all the articles in the blog. And get that linked from the front page.

**Comment by astronomersiva** [comment]
> We need a link to list all the articles in the blog.

We can create the blog's index like an archive...Something like [this](http://chennaiastronomyclub.org/archive/) but with more content.

> And get that linked from the front page.

Won't adding 'Blog' to the navbar solve this?

**Comment by bravegnu** [comment]
> Won't adding 'Blog' to the navbar solve this?

Sure. That is pretty much that needs to be done.

**Comment by astronomersiva** [comment]
@bravegnu @shrayasr , I am working on the first blog post. Here is a *very rough* abstract. Please tell me if this is on the right lines.

Chennaipy is glad to announce PySangamam, Tamil Nadu’s first Python Conference with support from organizers of other local user groups.

Through PySangamam,

We hope to promote the use of the Python programming language.
We hope to bring together Python developers in this region, to share ideas and learn from each other.
We hope to bring talented local developers to the fore-front, by providing, a platform to present their ideas, and showcase their projects.
We hope to bridge the gap between budding developers, and Python experts, by bringing them together, and providing spaces for interaction.

Dates
PySangamam will be held on September 7th(Friday) and September 8th(Saturday), 2018.

Venue
PySangamam will be held at the Industrial Consultancy and Sponsored Research building at IIT Madras.

IC & SR Near Gajendra Circle Opposite to Admin Building Indian Institute Of Technology Chennai, Tamil Nadu 600036

**Comment by shrayasr** [comment]
LGTM 👍

**Comment by astronomersiva** [comment]
Closed by #34 and #35
