### ISSUE TITLE
uBlock blocks Pipal & OrangeScape logos

### ISSUE THREAD

**Issue by shrayasr** [PySangamam/website#29]
With uBlock: 

![image](https://user-images.githubusercontent.com/240368/39684423-7b3e6a44-51d9-11e8-849a-21cfdbdbb1e8.png)

Without uBlock:

![image](https://user-images.githubusercontent.com/240368/39684434-8843f498-51d9-11e8-9b81-c4365ab9f65d.png)

Turns out this is because of using the class `.sponsor-logo` which is included in one of the blacklists

**Comment by bravegnu** [comment]
What is uBlock?

**Comment by bravegnu** [comment]
OK, got it. It is a content filtering plug-in. Now I see, what this is about.
