### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by astronomersiva** [PySangamam/website#3]
- [ ] Decide on content for the landing page.
- [x] Separate out FAQ Page.
- [x] Change contact number in the Code of Conduct.
- [ ] Redesign the venue map.
- [x] Put up a blog.
- [x] Sponsors list.
- [x] Twitter/Blog roll.
- [ ] Favicon.
- [ ] Cloudflare? Your views on this @shrayasr ?
- [x] Footer

**Comment by astronomersiva** [comment]
I am working on redesigning the map.

**Comment by shrayasr** [comment]
@astronomersiva wouldn't it be better to move it out as individual issues so that people from the @PySangamam/website can pick things up and move ahead?

**Comment by shrayasr** [comment]
Regarding Cloudflare, definitely a good thing to have. Any concerns about this @astronomersiva?

**Comment by syedjafer** [comment]
I am working on Twitter/blog roll . Twitter Blog roll is added . Also i need the blog location .

**Comment by astronomersiva** [comment]
@shrayasr , no concerns from my side too. Please go ahead and enable.

**Comment by shrayasr** [comment]
> I am working on Twitter/blog roll . Twitter Blog roll is added . Also i need the blog location .

@syedjafer. Blog is yet to be setup. It currently doesn't exist.

**Comment by shrayasr** [comment]
> @shrayasr , no concerns from my side too. Please go ahead and enable.

@astronomersiva let's do it as the last thing? Nothing has been setup on that end yet

**Comment by whiletruelearn** [comment]
@astronomersiva I think we also need to add the code of conduct also and  put it in some place which is easily seen in website.  
cc : @shrayasr

**Comment by shrayasr** [comment]
> I think we also need to add the code of conduct also and put it in some place which is easily seen in website.

Oh yes. Definitely. This needs to go on TODO

**Comment by syedjafer** [comment]
In Footer what are the things to be added .

**Comment by shrayasr** [comment]
PySangamam 2018 is 🎉 OVERRRR 🎉
