### ISSUE TITLE
Can we do away with GMaps in the home page?

### ISSUE THREAD

**Issue by astronomersiva** [PySangamam/website#38]
IMO, we can remove the usage of Google Maps as I don't think anybody ever uses it. We can maybe move it to the FAQ section with elaborate details on how to reach IIT from some major railway stations and bus stands in Chennai.

If we plan to organise some kind of transport from IIT gate to the venue and back, we can write about that also.

**Comment by shrayasr** [comment]
If this is the case, I'd rather be in its own "getting here" section rather than in the FAQ?

**Comment by shrayasr** [comment]
Also probably clicking "IC & SR - IIT Madras" on the landing page could take us here

**Comment by shrayasr** [comment]
Let's get more opinions. cc @bravegnu @zerothabhishek @gnurenga

**Comment by syedjafer** [comment]
Y we dont use OSM ?

**Comment by shrayasr** [comment]
PySangamam 2018 is 🎉 OVERRRR 🎉
