### ISSUE TITLE
Improve the site's performance with the help of Lighthouse

### ISSUE THREAD

**Issue by astronomersiva** [PySangamam/website#39]

**Comment by syedjafer** [comment]
Hi all , 
Some reports , 
![screenshot from 2018-05-14 08-44-06](https://user-images.githubusercontent.com/20949510/39976846-a3599024-5753-11e8-8753-138a4385db8b.png)
![screenshot from 2018-05-14 08-46-22](https://user-images.githubusercontent.com/20949510/39976847-a38f9e9e-5753-11e8-9f20-47ae1de93a79.png)
![screenshot from 2018-05-14 08-46-42](https://user-images.githubusercontent.com/20949510/39976848-a3bc20cc-5753-11e8-9097-a731af7693df.png)

**Comment by shrayasr** [comment]
PySangamam 2018 is 🎉 OVERRRR 🎉
