### ISSUE TITLE
Style hyperlinks to match with the theme

### ISSUE THREAD

**Issue by astronomersiva** [PySangamam/website#40]

**Comment by astronomersiva** [comment]
Do you want to take a shot at this @ragupathis ?

**Comment by syedjafer** [comment]
Shall i ?

**Comment by ragupathis** [comment]
Really sorry for the delayed response @astronomersiva ., Somewhere I missed this thing in my hurry.  Unfortunately at the moment i'm not available to take up this task, so Please go ahead with @syedjafer .

**Comment by syedjafer** [comment]
![screenshot from 2018-05-16 16-40-25](https://user-images.githubusercontent.com/20949510/40113687-eb06411c-5927-11e8-94d6-2fd5d5aa8f4b.png)

**Comment by astronomersiva** [comment]
Closed by #51
