### ISSUE TITLE
Add a link to CFP on the nav bar

### ISSUE THREAD

**Issue by shrayasr** [PySangamam/website#55]
The navigation bar doesn't contain a link to the CFP. The only way to currently reach it is: 

1. Via the "submit a proposal" button 
2. Via the blog post

Does it make sense to have a dedicated menu for it up in the nav bar?

**Comment by astronomersiva** [comment]
We can add a "Participate" item with sub items for CFP and tickets.

**Comment by shrayasr** [comment]
I'm skeptical about using drop downs for such crucial items on the menubar? Hiding it behind a click is not something I'd be OK with personally. What do you think?

**Comment by astronomersiva** [comment]
That is a fair point too. I will add these two (Y)

Edit: But this makes the navbar look too crowded to my taste. Let me know if this looks okay to you.
<img width="1440" alt="screen shot 2018-05-30 at 12 05 33 am" src="https://user-images.githubusercontent.com/7725225/40678165-601002b6-639d-11e8-81d7-0c00b3a1cf70.png">

**Comment by shrayasr** [comment]
Fair enough. It is crowded. But I don't know how else to make it better? Also the order can be 

`Home | Tickets | Submit proposal | Sponsors | Blog | FAQ | COC` ?

**Comment by shrayasr** [comment]
Closed via #68
