### ISSUE TITLE
Add STUDENT discount

### ISSUE THREAD

**Issue by bravegnu** [PySangamam/website#67]
Below the "Buy Tickets" and "Submit Proposal" buttons, we can include the text 'To avail student discount, use the discount code "STUDENT"'

@shrayasr @astronomersiva What do you guys think?

**Comment by astronomersiva** [comment]
Townscript already tells this in the ticket selection page right? I think it would make more sense to add this in the blog instead of the home page itself.

**Comment by bravegnu** [comment]
The problem is, it is not very obvious. For example in the mobile version, the details are hidden. The "apply discount link" is not very prominent.

**Comment by shrayasr** [comment]
> @shrayasr @astronomersiva What do you guys think?

+1 to this. Its not very visible. Don't know what % of people even read descriptions. Having it highlighted below the BUY NOW button would surely increase visibility, I think

**Comment by bravegnu** [comment]
Another suggestion is to do what PyCon India has done. Have a separate ticket section, that has table of ticket types and description with separate buy buttons, all linking back to the townscript page.

**Comment by bravegnu** [comment]
@astronomersiva Can we add a table as indicated in the above comment. See https://in.pycon.org/2018/ for an example.
