### ISSUE TITLE
Create Credits Page

### ISSUE THREAD

**Issue by bravegnu** [PySangamam/website#72]
The credits page needs to be created to list the people who have purchased contributor tickets, volunteers, and organizers.

**Comment by astronomersiva** [comment]
Please mail/comment the details Vijay...I'll put it up ASAP.

**Comment by gnurenga** [comment]
# Contributors 
V Karthik
Syed Nisar
Samuel Vijaykumar
Babu S K
Ravi Shankar

@bravegnu Above list took from our Telgram. Please Check data via Town script

**Comment by shrayasr** [comment]
- BABU SK
- Samuel Vijaykumar
- Amjidanutpan Ramanujam
- Nisar Sayed
- Karthik Viswanathan
- Ravi Shankar
- Vivek Radhakrishnan

This is the list :arrow_up:

**Comment by astronomersiva** [comment]
Should I add this to the navbar or will a blog post do?

**Comment by astronomersiva** [comment]
ping @shrayasr @bravegnu @gnurenga

**Comment by bravegnu** [comment]
I think we can add a link in the footer. Since this will contains names of volunteers and organizers, it is better not to put it on the nav bar :-)

**Comment by bravegnu** [comment]
We will start out with the list of people who have purchased contributor tickets and then we will add volunteers and organizers later on.

**Comment by bravegnu** [comment]
@shrayasr @gnurenga  Can we add the recent contributor ticket purchasers as well.

**Comment by astronomersiva** [comment]
@bravegnu, can we update this list once again?

**Comment by shrayasr** [comment]
Here's the final list for contributor tickets, @astronomersiva:

- Vijay Kumar B. 
- Senthil Kumaran S 
- Krishna Sangeeth 
- BABU SK 
- Samuel Vijaykumar 
- Amjidanutpan Ramanujam 
- Nisar Sayed 
- Karthik Viswanathan 
- Ravi Shankar 
- Vivek Radhakrishnan

**Comment by shrayasr** [comment]
I think we should also add **Suraj Sridhar** here since he helped us with designing the logo

**Comment by bravegnu** [comment]
@shrayasr @astronomersiva Sure we can add. But the contributor tickets are already up-to-date?
