### ISSUE TITLE
Add second keynote speaker

### ISSUE THREAD

**Issue by bravegnu** [PySangamam/website#77]
The second keynote speaker is Rushab, his bio needs to be taken and summarized from his LinkedIn profile page https://www.linkedin.com/in/rushabhmehta1/

**Comment by bravegnu** [comment]
Summarized from this profile:

Rushabh Mehta works with a passionate team and community to
revolutionize software used by small and medium sized organizations by
building a high quality, free and open source ERP called
ERPNext. Rushabh is the founder and CEO of Frappe Technologies, the
company behind ERPNext. At Frappe Technologies, his roles include
software development, design, marketing, accounting, testing,
vacuuming the floor, taking out the trash or whatever is the
bottleneck process.

**Comment by astronomersiva** [comment]
Will add this now (Y)

**Comment by shrayasr** [comment]
Closed via #78
