### ISSUE TITLE
Square logos look large

### ISSUE THREAD

**Issue by bravegnu** [PySangamam/website#82]
I think, currently logos are dimensioned by their width. I think this is not the best approach. Since logos are usually square or landscaped, it is better to dimension them by their height.

**Comment by bravegnu** [comment]
@astronomersiva @shrayasr Your thoughts.

**Comment by shrayasr** [comment]
👍 I agree

**Comment by bravegnu** [comment]
@astronomersiva Can you help us out with this?

**Comment by astronomersiva** [comment]
I will take a look at this 👍

**Comment by shrayasr** [comment]
Is this done? @astronomersiva
