### ISSUE TITLE
Prepare for Schedule Announcement

### ISSUE THREAD

**Issue by bravegnu** [PySangamam/website#83]
We will be announcing the schedule shortly. Need to come up with a template and placement for the schedule. @astronomersiva can you please look into this?

**Comment by astronomersiva** [comment]
Time, title, a brief description and speaker name should be sufficient right?

**Comment by bravegnu** [comment]
The description might not be required in the schedule. We can have one blog article with the details of each talk, and have links from the schedule to the blog article.

**Comment by bravegnu** [comment]
@astronomersiva Can we get this https://pysangamam.org/blog/2018/08/14/schedule/ on the front page with links back to https://pysangamam.org/blog/2018/08/11/announcing-selected-talks/ from each talk?

**Comment by bravegnu** [comment]
@astronomersiva We need to add the schedule to the front page. Can we get this done by tomorrow?

**Comment by astronomersiva** [comment]
I am on it 👍

**Comment by bravegnu** [comment]
@astronomersiva You rock man!

**Comment by bravegnu** [comment]
@astronomersiva A few suggestions. The icon for the conference is not visible for me, can we use an icon instead? Also, I would still prefer to see the schedule on the front page, similar to https://in.pycon.org/2017/ Is it possible?

**Comment by astronomersiva** [comment]
@bravegnu thanks 😇!

> The icon for the conference is not visible for me, can we use an icon instead

That's strange, I had just used an emoji...so it should be visible as we have already specified utf-8 encoding in the meta 😕

> Also, I would still prefer to see the schedule on the front page, similar to https://in.pycon.org/2017/ Is it possible?

Yup, should be easy. Will raise a PR in a while.


Also,  apologies for the delay with this. I had been held up this week.

**Comment by bravegnu** [comment]
@astronomersiva May be I do not have the required font support?

**Comment by astronomersiva** [comment]
Will something like this be sufficient?

<img width="1436" alt="screen shot 2018-08-19 at 8 39 00 pm" src="https://user-images.githubusercontent.com/7725225/44310196-edfb9800-a3ef-11e8-9bf5-50583e165f31.png">

**Comment by bravegnu** [comment]
@astronomersiva That looks great!

**Comment by bravegnu** [comment]
@astronomersiva Great going! Now that we have the schedule on the front page, the link to the schedule can be removed.

**Comment by bravegnu** [comment]
@astronomersiva Also we are planning to have a workshop track, I am not sure if the current data model for the schedule will be suitable if an additional track, especially when the timeslots (workshops are 2.5 hours) do not match. Please do give a thought about this.

**Comment by astronomersiva** [comment]
@bravegnu, do we have the workshop schedule ready?

**Comment by bravegnu** [comment]
@astronomersiva The workshop schedule is out. https://pysangamam.org/blog/2018/09/04/announcing-workshops/ Can we integrate that into the overall schedule?
