### ISSUE TITLE
Prepare for including logo

### ISSUE THREAD

**Issue by bravegnu** [PySangamam/website#91]
The logo needs to be added to the landing page. The logo is available from https://github.com/PySangamam/art/blob/master/logo/pysangamam-logo.png

**Comment by bravegnu** [comment]
@astronomersiva Can you please look into this?

**Comment by astronomersiva** [comment]
Still wondering where to add this 🤔

**Comment by bravegnu** [comment]
We need to ditch the "PySangamam" text, to accommodate the logo + text.

**Comment by astronomersiva** [comment]
I'll take a shot at this...do we have an SVG available? Also, if we can get the floral design that was used in the logo separately, I can add them to several other places in the site.

**Comment by bravegnu** [comment]
@astronomersiva It is in the art repo https://github.com/pysangamam/art

**Comment by bravegnu** [comment]
@astronomersiva We made the logo announcement, we need to get the logo on the website. Can we do this today?

**Comment by astronomersiva** [comment]
I missed your reply @bravegnu! Let me finish this. The [SVG version](https://raw.githubusercontent.com/PySangamam/art/master/logo/pysangamam-logo.svg) doesn't have the kural in it.

Edit: I settled for the vertical version. I made a few edits to the SVG as it had a white background and all.

**Comment by bravegnu** [comment]
@astronomersiva I guess you don't have the font. I am fixing that, converting the text to curves.

**Comment by bravegnu** [comment]
@astronomersiva Done!

**Comment by astronomersiva** [comment]
<img width="1440" alt="screen shot 2018-08-29 at 10 54 12 pm" src="https://user-images.githubusercontent.com/7725225/44804270-7b07d380-abde-11e8-9a1a-214e39c6ad4e.png">

**Comment by astronomersiva** [comment]
@bravegnu please take a look^

**Comment by bravegnu** [comment]
@astronomersiva The vertical variant was done for creating the T-Shirt template, and has colors reduced to 2. Can we use the horizontal variant instead?

**Comment by astronomersiva** [comment]
@bravegnu I edited the SVG to add colors :D

BTW, the actual reason why I settled for that SVG was that the normal one takes a lot of space due to the logo..I think this pic will make it clearer
<img width="1440" alt="screen shot 2018-08-29 at 11 00 40 pm" src="https://user-images.githubusercontent.com/7725225/44804655-958e7c80-abdf-11e8-92c2-f3960e09b2cc.png">

**Comment by bravegnu** [comment]
@astronomersiva Hmm... looks OK to me though. May be I am just too drowsy to see the problem.

**Comment by astronomersiva** [comment]
@bravegnu, do you have only the logo(the Python logo) somewhere? I was thinking of adding that as the favicon.

**Comment by shrayasr** [comment]
> @bravegnu, do you have only the logo(the Python logo) somewhere? I was thinking of adding that as the favicon.

We'll ask babu for this. Should be possible

**Comment by bravegnu** [comment]
@astronomersiva No, but we can make one available.
