### ISSUE TITLE
meta tags should show the right page

### ISSUE THREAD

**Issue by shrayasr** [PySangamam/website#93]
Currently whenever we post something from pysangamam.org anywhere - Twitter / WhatsApp / etc we only get one kind of preview: 

![image](https://user-images.githubusercontent.com/240368/44942153-3d1ad300-adc9-11e8-87b1-6e1a67fbd97c.png)

⬆️ (This is in Telegram)

Can we make it so that _that specific_ page details are shared?

**Comment by shrayasr** [comment]
This was when I shared the https://pysangamam.org/credits page link

**Comment by shrayasr** [comment]
I'd assume its because the open graph meta is hard coded(?) to 

```
<meta property="og:title" content="Tamil Nadu's First Python Conference" />
<meta property="og:description" content="September 7th and 8th, 2018 IC & SR - IIT Madras" />
<meta property="og:url" content="http://pysangamam.org/" />
<meta property="og:image" content="img/python-logo.png" />
<meta property="og:type" content="article" />
```

**Comment by astronomersiva** [comment]
Yes @shrayasr, it looks like all the meta tags are hardcoded. I am fixing it.

**Comment by astronomersiva** [comment]
Created #94 for this.
